[package]
name = "web-view"
version = "0.1.3"
authors = ["Boscop"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/Boscop/web-view"
description = "Rust bindings for webview, a tiny cross-platform library to render web-based GUIs for desktop applications"
keywords = ["web", "gui", "desktop", "electron", "webkit"]
categories = ["gui", "web-programming", "api-bindings", "rendering", "visualization"]
exclude = ["examples/todo-ps/dist/**/*"]

[dependencies]
fnv = "1.0"

[dev-dependencies]
urlencoding = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[build-dependencies]
cc = "1"
pkg-config = "0.3"
